//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du köpa hus i Spanien, lägenhet i Frankrike eller en strandvilla i Thailand, då har du hittat rätt.
        ///Mowido grundades för oss som älskar semester utomlands och drömmer om ett andra hem i fjärran
        ///land. På Mowido samlar vi bostadsannonser från de populäraste semesterorterna för oss svenskar.
        ///Alla annonser på vår sida säljs av registrerade mäklare så du kan vara säker på att din bostadsaffär
        ///sköts enligt konstens alla regler.
        ///&lt;br /&gt;
        ///Knappa in ett land, stad eller område i sökrutan och du får fram mat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us - Mowido.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drömmer du också om att köpa bostad utomlands?.
        /// </summary>
        public static string About_TextHeader {
            get {
                return ResourceManager.GetString("About_TextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About real estate agent.
        /// </summary>
        public static string AboutBroker {
            get {
                return ResourceManager.GetString("AboutBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannes.
        /// </summary>
        public static string Cannes {
            get {
                return ResourceManager.GetString("Cannes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact.
        /// </summary>
        public static string Fact {
            get {
                return ResourceManager.GetString("Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your dreamhouse.
        /// </summary>
        public static string Find_Dreamhouse {
            get {
                return ResourceManager.GetString("Find_Dreamhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For sale:.
        /// </summary>
        public static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your house abroad.
        /// </summary>
        public static string Header_Default {
            get {
                return ResourceManager.GetString("Header_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your house, appartment or garden.
        /// </summary>
        public static string Header_FindHouse {
            get {
                return ResourceManager.GetString("Header_FindHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes for sale.
        /// </summary>
        public static string Header_SearchPlace {
            get {
                return ResourceManager.GetString("Header_SearchPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koh Lanta.
        /// </summary>
        public static string KohLanta {
            get {
                return ResourceManager.GetString("KohLanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisboa.
        /// </summary>
        public static string Lisboa {
            get {
                return ResourceManager.GetString("Lisboa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living space.
        /// </summary>
        public static string LivingSpace {
            get {
                return ResourceManager.GetString("LivingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaga.
        /// </summary>
        public static string Malaga {
            get {
                return ResourceManager.GetString("Malaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more about the property.
        /// </summary>
        public static string Map_Readmore {
            get {
                return ResourceManager.GetString("Map_Readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your house abroad in {0}. Search over 10 000 houses, appartments and gardens at Mowido..
        /// </summary>
        public static string MetaDesc_SERP {
            get {
                return ResourceManager.GetString("MetaDesc_SERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitta ditt hus utomlands hos Mowido. Hos Mowido finns över 10 000 hus, lägenheter och tomter över hela världen..
        /// </summary>
        public static string MetaDesc_Startpage {
            get {
                return ResourceManager.GetString("MetaDesc_Startpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly charge.
        /// </summary>
        public static string MonthlyCharge {
            get {
                return ResourceManager.GetString("MonthlyCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice.
        /// </summary>
        public static string Nice {
            get {
                return ResourceManager.GetString("Nice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No price.
        /// </summary>
        public static string NoPrice {
            get {
                return ResourceManager.GetString("NoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string NumberOfRooms {
            get {
                return ResourceManager.GetString("NumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mowido - Find your property world wide.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot size.
        /// </summary>
        public static string PlotSize {
            get {
                return ResourceManager.GetString("PlotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PMenu_About {
            get {
                return ResourceManager.GetString("PMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string PMenu_Map {
            get {
                return ResourceManager.GetString("PMenu_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More pictures.
        /// </summary>
        public static string PMenu_Pictures {
            get {
                return ResourceManager.GetString("PMenu_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About broker.
        /// </summary>
        public static string PMenu_Seller {
            get {
                return ResourceManager.GetString("PMenu_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map location.
        /// </summary>
        public static string Product_Map {
            get {
                return ResourceManager.GetString("Product_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures of the house.
        /// </summary>
        public static string Product_Pictures {
            get {
                return ResourceManager.GetString("Product_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more about this property.
        /// </summary>
        public static string Product_ReadMore {
            get {
                return ResourceManager.GetString("Product_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more pictures.
        /// </summary>
        public static string Product_ViewPictures {
            get {
                return ResourceManager.GetString("Product_ViewPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country, Area or City....
        /// </summary>
        public static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to broker.
        /// </summary>
        public static string Search_SellerLink {
            get {
                return ResourceManager.GetString("Search_SellerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to houses.
        /// </summary>
        public static string Slug_Search_Start {
            get {
                return ResourceManager.GetString("Slug_Search_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest houses abroad for sale.
        /// </summary>
        public static string Start_Header {
            get {
                return ResourceManager.GetString("Start_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your house abroad.
        /// </summary>
        public static string StartTop_Header {
            get {
                return ResourceManager.GetString("StartTop_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        public static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 4 Countries and Cities.
        /// </summary>
        public static string Top4ContryCity {
            get {
                return ResourceManager.GetString("Top4ContryCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Cities.
        /// </summary>
        public static string Top5City {
            get {
                return ResourceManager.GetString("Top5City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Countries.
        /// </summary>
        public static string Top5Country {
            get {
                return ResourceManager.GetString("Top5Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TopMenu_About {
            get {
                return ResourceManager.GetString("TopMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string TopMenu_Buy {
            get {
                return ResourceManager.GetString("TopMenu_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying a home.
        /// </summary>
        public static string TopMenu_BuyingHome {
            get {
                return ResourceManager.GetString("TopMenu_BuyingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find house.
        /// </summary>
        public static string TopMenu_FindHouse {
            get {
                return ResourceManager.GetString("TopMenu_FindHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string TopMenu_Sell {
            get {
                return ResourceManager.GetString("TopMenu_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /about.
        /// </summary>
        public static string Url_About {
            get {
                return ResourceManager.GetString("Url_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /buy-home.
        /// </summary>
        public static string Url_BuyingHome {
            get {
                return ResourceManager.GetString("Url_BuyingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to houses.
        /// </summary>
        public static string Url_FindHouse {
            get {
                return ResourceManager.GetString("Url_FindHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Url_Login {
            get {
                return ResourceManager.GetString("Url_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to house.
        /// </summary>
        public static string Url_Product {
            get {
                return ResourceManager.GetString("Url_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year built.
        /// </summary>
        public static string YearBuilt {
            get {
                return ResourceManager.GetString("YearBuilt", resourceCulture);
            }
        }
    }
}
